from time import sleep
from selenium import webdriver
from selenium.webdriver import ActionChains
from selenium.webdriver.support.select import Select
driver = webdriver.Edge (executable_path="D:/browserdrivers/msedgedriver.exe")
driver.maximize_window()
driver.get("http://laptop-nrp52uus/SaralTDS/Authentication/Login.aspx")
dd = driver.find_element("xpath","//select[@id='ddlFinYear']")
s = Select(dd)
sleep(2)
s.select_by_index(9)
sleep(2)
s.select_by_value("2020")
sleep(2)
s.select_by_visible_text("2021-22")
sleep(2)
driver.find_element("id","txtUsername").send_keys("admin")
driver.find_element("id","txtPassword").send_keys("admin@009")
driver.find_element("id","btnLogin").click()
sleep(2)
driver.find_element("id","txtSearch").click()
sleep(2)
driver.find_element("id","txtSearch").send_keys("head office")
driver.find_element("xpath","//*[@id='lstBranches']/option").click()
driver.find_element("id","btnSelect").click()
# driver.find_element("css selector","a[class='ctl00_mnuTDS_1 ctl00_mnuTDS_3']").click()
# driver.find_element("css selector", 'a#ctl00_contentPlaceHolderBody_btnShowForm26').click()
# driver.find_element("xpath","(//a[@class='homelb'])[3]").click()
act = ActionChains(driver)
Masters = driver.find_element("xpath","//a[.='Masters']")
sleep(2)
act.move_to_element(Masters).perform()
deductor =driver.find_element("xpath","/html/body/form/div[3]/div[2]/div[1]/div/div[2]/table/tbody/tr/td/div[3]/table/tbody/tr[2]/td/table/tbody/tr/td/a")
act.move_to_element(deductor).perform()
deductor.click()
sleep(2)
# Default_Settings = driver.find_element("xpath", "//a[.='Default Settings']")
# act.move_to_element(Default_Settings).perform()
# Settings = driver.find_element("xpath", "//a[.='Settings']")
# act.move_to_element(Settings).perform()
# pdf_sign = driver.find_element("partial link text", "eSign Setting")
# act.move_to_element(pdf_sign).perform()
# pdf_sign.click()
# sleep(2)
driver.implicitly_wait(2)
# driver.find_element("id","ctl00_lnkLogout").click()
